"""add video classification, alert, and summary tables

Revision ID: 1e6551f1e7f7
Revises: d6b07cf94800
Create Date: 2025-07-04 07:40:38.551468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6551f1e7f7'
down_revision: Union[str, Sequence[str], None] = 'd6b07cf94800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_alerts_id'), 'video_alerts', ['id'], unique=False)
    op.create_table('video_classifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_classifications_id'), 'video_classifications', ['id'], unique=False)
    op.create_table('video_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('summary_text', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_summaries_id'), 'video_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_summaries_id'), table_name='video_summaries')
    op.drop_table('video_summaries')
    op.drop_index(op.f('ix_video_classifications_id'), table_name='video_classifications')
    op.drop_table('video_classifications')
    op.drop_index(op.f('ix_video_alerts_id'), table_name='video_alerts')
    op.drop_table('video_alerts')
    # ### end Alembic commands ###
